package dev.byrt.burb.music

import dev.byrt.burb.library.Sounds

import net.kyori.adventure.sound.Sound

enum class Music(val track: Sound, val trackLengthSecs: Int) {
    LOBBY_TITLE_SCREEN(Sounds.Music.LOBBY_TITLE_SCREEN, 139),
    LOBBY_WAITING(Sounds.Music.LOBBY_WAITING, 59),
    LOBBY_UNDERWORLD(Sounds.Music.LOBBY_UNDERWORLD, 66),
    LOBBY_UNDERWORLD_CHALLENGE_LOW(Sounds.Music.LOBBY_UNDERWORLD_CHALLENGE_LOW, 8),
    LOBBY_UNDERWORLD_CHALLENGE_MEDIUM(Sounds.Music.LOBBY_UNDERWORLD_CHALLENGE_MEDIUM, 14),
    LOBBY_UNDERWORLD_CHALLENGE_HIGH(Sounds.Music.LOBBY_UNDERWORLD_CHALLENGE_HIGH, 14),
    LOBBY_UNDERWORLD_CHALLENGE_INTENSE(Sounds.Music.LOBBY_UNDERWORLD_CHALLENGE_INTENSE, 19),
    LOADING_MELODY(Sounds.Music.LOADING_MELODY, 148),
    SUBURBINATION_PLANTS(Sounds.Music.SUBURBINATION_PLANTS, 58),
    SUBURBINATION_ZOMBIES(Sounds.Music.SUBURBINATION_ZOMBIES, 58),
    RANDOM_LOW(Sounds.Music.RANDOM_LOW, 60),
    RANDOM_MEDIUM(Sounds.Music.RANDOM_MEDIUM, 60),
    RANDOM_HIGH(Sounds.Music.RANDOM_HIGH, 60),
    TREASURE_TIME_LOW(Sounds.Music.TREASURE_TIME_LOW, 70),
    TREASURE_TIME_HIGH(Sounds.Music.TREASURE_TIME_HIGH, 70),
    VANQUISH_SHOWDOWN(Sounds.Music.VANQUISH_SHOWDOWN, 122),
    RANDOS_REVENGE(Sounds.Music.RANDOS_REVENGE, 60),
    OVERTIME(Sounds.Music.OVERTIME_MUSIC, 60),
    POST_GAME(Sounds.Music.POST_GAME_MUSIC, 80),
    DOWNTIME_LOOP(Sounds.Music.DOWNTIME_LOOP, 191),
    DOWNTIME_SUSPENSE(Sounds.Music.DOWNTIME_SUSPENSE, 219),
    NULL(Sounds.Music.NULL, Int.MAX_VALUE)
}