name: Burb
version: "${version}"
main: dev.byrt.burb.Main
api-version: "1.21"
authors: [Byrt, Flamey]
description: Doing the world a favour by providing PVZ:GW's "Suburbination" in Minecraft.
website: https://bigrat.monster
